export const FETCH_TASK_ITEM = 'FETCH_TASK_ITEM'
export const FETCH_TASK_ITEM_SUCCESS = 'FETCH_TASK_ITEM_SUCCESS'
export const FETCH_TASK_ITEM_FAILED = 'FETCH_TASK_ITEM_FAILED'

export const ADD_TASK_ITEM = 'ADD_TASK_ITEM'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'

export const UPDATE_TASK_ITEM = 'UPDATE_TASK_ITEM'
export const UPDATE_TASK_ITEM_SUCCESS = 'UPDATE_TASK_ITEM_SUCCESS'
export const UPDATE_TASK_ITEM_FAILED = 'UPDATE_TASK_ITEM_FAILED'

export const DELETE_TASK_ITEM = 'DELETE_TASK_ITEM'
export const DELETE_TASK_ITEM_SUCCESS = 'DELETE_TASK_ITEM_SUCCESS'
export const DELETE_TASK_ITEM_FAILED = 'DELETE_TASK_ITEM_FAILED'